name: Publish Docker image
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */8 * * *
  workflow_dispatch: {}

jobs:
  ecr_public:
    name: ECR Public
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    env:
      REGISTRY_NAME: public.ecr.aws/mats
      REPO_NAME: devcontainer-for-aws
    steps:
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Build
        id: build
        run: |
          docker build -t devcontainer:latest ./.devcontainer
          docker tag devcontainer:latest $REGISTRY_NAME/$REPO_NAME:${{ steps.sha.outputs.sha7 }}
          docker tag devcontainer:latest $REGISTRY_NAME/$REPO_NAME:latest
      - name: Push to ECR Public
        id: push
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY_NAME
          docker push $REGISTRY_NAME/$REPO_NAME:${{ steps.sha.outputs.sha7 }}
          docker push $REGISTRY_NAME/$REPO_NAME:latest

